inherit_mode:
  merge:
    - Exclude

plugins:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  Exclude:
    - Gemfile
    - Gemfile.lock
    - Rakefile
    - bin/**/*
    - _site/**/*

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - test/**/*

Metrics/ClassLength:
  Max: 200

Metrics/MethodLength:
  Max: 20

Minitest/MultipleAssertions:
  Max: 10

Naming/PredicateMethod:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false
