# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Kevin Aktug's Portfolio
# base64 encoded
email: a2V2aW5Aa21hZ2FtZWd1eS5jb20=
description: >- # this means to ignore newlines until "author:"
  Kevin Aktug's Portfolio Site
author: Kevin Aktug
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kmagameguy.com" # the base hostname & protocol for your site, e.g. http://example.com
lang: "en_US"

# For Pages
social_links:
  - name: email
    link: "#"
    decodeFlag: true
  - name: linkedin
    link: &linkedin_link https://www.linkedin.com/in/kmagameguy
  - name: github
    link: &github_link https://github.com/kmagameguy
  - name: youtube
    link: &youtube_link https://www.youtube.com/kmagameguy
  - name: soundcloud
    link: &soundcloud_link https://soundcloud.com/serpent_scales

# SEO
social:
  links:
    - *linkedin_link
    - *github_link
    - *youtube_link
    - *soundcloud_link

employer:
  name: Custom Ink
  job: Customer Care Technology Manager
  url: https://www.customink.com

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-autoprefixer
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10
paginate_path: "blog/page:num/"

sass:
  sass_dir: assets/css

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
